flags: {}
packages:
- '.'
- location:
      git: https://github.com/agrafix/Spock.git
      commit: 2c60a48b2c0be0768071cc1b3c7f14590ffcc7d6
  subdirs:
    - Spock
    - Spock-core
    - reroute
- location:
      git: https://github.com/agrafix/Spock-digestive.git
      commit: 4c85647427e21bbaefbf04c4bc315d4bdfabba0e
extra-deps:
- digestive-bootstrap-0.1.0.1
- blaze-bootstrap-0.1.0.1
- digestive-functors-blaze-0.6.0.6
resolver: lts-5.8
